var annotated_dup =
[
    [ "GuiPackage", "namespace_gui_package.html", "namespace_gui_package" ],
    [ "_FreezableController", "class___freezable_controller.html", null ],
    [ "_FreezableController< T, true >", "class___freezable_controller_3_01_t_00_01true_01_4.html", "class___freezable_controller_3_01_t_00_01true_01_4" ],
    [ "AABBCollider", "struct_a_a_b_b_collider.html", "struct_a_a_b_b_collider" ],
    [ "AudioInterface", "struct_audio_interface.html", "struct_audio_interface" ],
    [ "Backend", "class_backend.html", "class_backend" ],
    [ "CircleCollider", "struct_circle_collider.html", "struct_circle_collider" ],
    [ "Collider", "struct_collider.html", "struct_collider" ],
    [ "ColliderComponent", "struct_collider_component.html", "struct_collider_component" ],
    [ "CollisionPartition", "struct_collision_partition.html", "struct_collision_partition" ],
    [ "Controller", "class_controller.html", "class_controller" ],
    [ "ControllerManager", "class_controller_manager.html", "class_controller_manager" ],
    [ "DummyAudioInterface", "struct_dummy_audio_interface.html", "struct_dummy_audio_interface" ],
    [ "DummyEventInterface", "struct_dummy_event_interface.html", "struct_dummy_event_interface" ],
    [ "DummyFileInterface", "struct_dummy_file_interface.html", "struct_dummy_file_interface" ],
    [ "DummyGraphicsInterface", "struct_dummy_graphics_interface.html", "struct_dummy_graphics_interface" ],
    [ "Engine", "class_engine.html", "class_engine" ],
    [ "EventInterface", "struct_event_interface.html", "struct_event_interface" ],
    [ "EventListener", "class_event_listener.html", "class_event_listener" ],
    [ "FileInterface", "struct_file_interface.html", "struct_file_interface" ],
    [ "GameObject", "class_game_object.html", "class_game_object" ],
    [ "GameState", "class_game_state.html", "class_game_state" ],
    [ "GraphicsInterface", "struct_graphics_interface.html", "struct_graphics_interface" ],
    [ "GraphicsManager", "class_graphics_manager.html", "class_graphics_manager" ],
    [ "Key", "struct_key.html", "struct_key" ],
    [ "Manifold", "struct_manifold.html", "struct_manifold" ],
    [ "Node", "class_node.html", "class_node" ],
    [ "ObjectComponent", "struct_object_component.html", "struct_object_component" ],
    [ "Package", "class_package.html", "class_package" ],
    [ "Packageable", "struct_packageable.html", "struct_packageable" ],
    [ "PhysicsManager", "class_physics_manager.html", "class_physics_manager" ],
    [ "Point", "struct_point.html", "struct_point" ],
    [ "PointCollider", "struct_point_collider.html", "struct_point_collider" ],
    [ "Rectangle", "struct_rectangle.html", "struct_rectangle" ],
    [ "RenderData", "struct_render_data.html", "struct_render_data" ],
    [ "RigidBodyComponent", "struct_rigid_body_component.html", "struct_rigid_body_component" ],
    [ "SpriteComponent", "struct_sprite_component.html", "struct_sprite_component" ],
    [ "Stack", "class_stack.html", "class_stack" ],
    [ "StateManager", "class_state_manager.html", "class_state_manager" ],
    [ "StateManipulator", "class_state_manipulator.html", "class_state_manipulator" ],
    [ "TagHandler", "class_tag_handler.html", null ],
    [ "TransformComponent", "struct_transform_component.html", "struct_transform_component" ],
    [ "TriggerListener", "class_trigger_listener.html", "class_trigger_listener" ],
    [ "Vector2d", "struct_vector2d.html", "struct_vector2d" ]
];